@url=localhost:3001/api/users

GET {{url}}
Accept: application/json

###
GET {{url}}/b84567bc-bec1-4a0a-bae4-4827154c70ba
Accept: application/json

###
POST {{url}}
Content-Type: application/json

{
  "username": "user2",
  "firstName": "User2",
  "lastName": "User",
  "password": "userpw",
  "email": "sasanga@gmail.com",
  "roleId": "d1efc6cc-5375-4e63-82cf-582d0346e70e"
}
