@url=localhost:3001/api/users

GET {{url}}
Accept: application/json

###
GET {{url}}/de774f36-f664-47b6-a15f-63f2c8a68ff9
Accept: application/json

###
POST {{url}}
Content-Type: application/json

{
  "username": "sasanga",
  "firstName": "Sasanga",
  "lastName": "Edirisinghe",
  "password": "sasa90",
  "email": "sasanga@gmail.com",
  "roleId": "7948a34a-4bc9-4658-833e-2f6dea9a3a51"
}
